name: Deploy to VITE_HOSTinger VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: .env

    steps:
      - name: 🛠 Checkout Repository
        uses: actions/checkout@v3

      - name: ⚙ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔨 Build Vite Project
        run: npm run build

      - name: 🔍 Verify Build Output
        run: ls -la dist || echo "⚠ dist folder is missing or empty!"

      - name: 🖥 Ensure Deployment Directory Exists on VPS
        uses: appleboy/ssh-action@master
        with:
          VITE_HOST: ${{ secrets.VITE_HOSTINGER_VITE_HOST }}
          username: ${{ secrets.VITE_HOSTINGER_USERNAME }}
          key: ${{ secrets.VITE_HOSTINGER_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/organic-origin/dist

      - name: 🚀 Deploy Build to VPS
        uses: appleboy/scp-action@master
        with:
          VITE_HOST: ${{ secrets.VITE_HOSTINGER_VITE_HOST }}
          username: ${{ secrets.VITE_HOSTINGER_USERNAME }}
          key: ${{ secrets.VITE_HOSTINGER_SSH_KEY }}
          port: 22
          source: "dist/*"
          target: "/var/www/organic-origin"